oss:
  endpoint: "oss-cn-zhangjiakou.aliyuncs.com"
  access_key_id: ""
  access_key_secret: ""
  expire_seconds: 60
resource_pack:
  limit_seconds: 1800
  prompt: <yellow>Hello!
  force: false

packs:
  pack1:
    oss_path:
      bucket_name: g2213swo
      pack_path: assets/pack.zip # 文件路径
  pack2:
    oss_path:
      bucket_name: mimaru
      pack_path: assets/dev.zip

# 所有服务器的默认材质包, 当服务器没有配置材质包时使用
server_default: []

servers:
  lobby:
    - pack1
    - pack2