oss:
  endpoint: "oss-cn-zhangjiakou.aliyuncs.com"
  access_key_id: ""
  access_key_secret: ""
  expire_seconds: 60
resource_pack:
  limit_seconds: 1800
  prompt: <yellow>Hello!
  force: false

packs:
  pack1:
    oss_path:
      bucket_name: g2213swo
      pack_prefix: assets/ # Required path prefix. E.g., assets/
      pack_name: pack.zip # Required type: application/zip
      pack_hash: ""
  pack2:
    oss_path:
      bucket_name: mimaru
      pack_prefix: assets/
      pack_name: dev.zip
      pack_hash: ""

servers:
  lobby:
    - pack1
    - pack2

server_default: []